### ISSUE TITLE
Airflow task retry_delay is used for a different purpose

### ISSUE THREAD

**Issue by jamesl2014** [spotinst/ocean-spark-airflow-provider#8]
I find out OceanSparkOperator retry_delay parameter is used to setup how often to call Ocean Spark API, but its original purpose is to setup task retry delay.

**Comment by waldoppper** [comment]
Indeed, if your DAG supplies default a default "retry_delay" argument, it will be of type `datetime.timedelta`.
When OceanSparkOperator receives this default, it then attempts to [wrap it again](https://github.com/spotinst/ocean-spark-airflow-provider/blob/v0.1.3/ocean_spark/operators.py#L69)

The result is a stacktrace at DAG-parse time like this:
```python
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/monorepo/airflow/dags/adperf_airflow/dags/canary_dag.py", line 42, in <module>
    business_area='ADVERTISING'
  File "/monorepo/airflow/dags/common/airflow/canary_dag/canary_dag_builder.py", line 192, in hatch_canary
    "cores": 1,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/ocean_spark/operators.py", line 69, in __init__
    self.retry_delay = timedelta(seconds=retry_delay)
TypeError: unsupported type for timedelta seconds component: datetime.timedelta
```

My workaround for now is to re-provide a the task-instance the `int` argument that it's expecting:
```python
OceanSparkOperator(
          ...
          dag=dag,
          retry_delay=1,  # manually provide this to override our DAG-level default
          ...
      )
```
